#!/bin/sh
#
# Postinst script for psi-client
#

set -e

NAME=psi-client
HOME=/var/run/psi-client

# Create psi-client user and its homedir
if ! getent passwd $NAME >/dev/null; then
	adduser --system --home $HOME --shell /bin/sh --disabled-password $NAME
fi

if ! [ -d $HOME ]; then
	mkdir -p $HOME
	chmod 755 $HOME
	chown -h -R $NAME $HOME
fi

#DEBHELPER#
